export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAIL = 'FETCH_CATEGORIES_FAIL';
export const STORE_QUIZ_CATEGORY = 'STORE_QUIZ_CATEGORY';
export const STORE_QUIZ_LEVEL = 'STORE_QUIZ_LEVEL';
export const STORE_NUMBER_OF_QUESTIONS = 'STORE_NUMBER_OF_QUESTIONS '; 